[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'lambdalisue/vim-gista'
if = '''!has('nvim')'''

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
  source ~/.vim/rc/color.vim
'''

# [[plugins]]
# repo = 'vim-jp/vimdoc-ja'

# [[plugins]]
# repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'junegunn/fzf'
hook_add = '''
  source ~/.vim/rc/fzf.vim
'''

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  source ~/.vim/rc/lightline.vim
'''

[[plugins]]
repo = 'cocopon/lightline-hybrid.vim'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'kana/vim-submode'
hook_add = '''
  source ~/.vim/rc/submode.vim
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  source ~/.vim/rc/quickrun.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'KazuakiM/vim-qfstatusline'
hook_add = '''
  " :WatchdogsRun後にlightline.vimを更新
  let g:Qfstatusline#UpdateCmd = function('lightline#update')
'''

# [[plugins]]
# repo = 'osyo-manga/vim-automatic'
# hook_add = '''
#   source ~/.vim/rc/automatic.vim
# '''
