[[plugins]]
repo = 'mattn/emmet-vim'
on_i = 1

[[plugins]]
repo = 'tyru/caw.vim'
on_i = 1

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_i = 1

[[plugins]]
repo = 'tpope/vim-endwise'
on_i = 1

[[plugins]]
repo = 'tpope/vim-surround'
on_path = '.*'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_source = '''
  let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
# repo = 'kannokanno/previm'
repo = 'kazuph/previm'
rev = 'feature/add-plantuml-plugin'
on_ft = ['markdown', 'text', 'rst']
hook_source = '''
  let g:previm_enable_realtime = 1
	let g:previm_show_header = 0
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_path = '.*'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
on_path = '.*'
hook_source = '''
  let g:extra_whitespace_ignored_filetypes = ['unite', 'quickrun', 'dbext']
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
on_path = '.*'

[[plugins]]
repo = 'tpope/vim-fugitive'
on_path = '.*'

[[plugins]]
repo = 'kana/vim-smartinput'
on_i = 1

# set relativenumber は全画面再描画されるため重いらしい
# iterm2 ではそんなに重くない感じ
[[plugins]]
repo = 'jeffkreeftmeijer/vim-numbertoggle'
on_i = 1

[[plugins]]
repo = 'kana/vim-textobj-user'
on_i = 1

[[plugins]]
repo = 'kana/vim-textobj-entire'
on_i = 1

[[plugins]]
repo = 'tpope/vim-abolish'
on_path = '.*'

[[plugins]]
repo = 'vim-scripts/confluencewiki.vim'
on_ft = 'confluencewiki'

[[plugins]]
repo = 'davidhalter/jedi-vim'
if = '''!has('nvim')'''
on_ft = ['python', 'htmldjango', 'markdown']
hook_post_update = '''
  let cmd = 'pip install jedi'
  let g:dein#plugin.build = cmd
'''
hook_source = '''
  " quickrunと被るため大文字に変更
  let g:jedi#rename_command = '<Leader>R'
'''

[[plugins]]
repo = 'lambdalisue/vim-django-support'
on_ft = ['python', 'htmldjango']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = '''has('nvim')'''
on_i = 1
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
if = '''has('nvim')'''
on_ft = ['python', 'htmldjango', 'markdown']
hook_post_update = '''
  let cmd = 'pip install neovim jedi'
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python', 'htmldjango']

[[plugins]]
repo = 'lambdalisue/vim-pyenv'
on_ft = ['python', 'htmldjango']

#[[plugins]]
#repo = 'scrooloose/syntastic'
##if = '''has('vim')'''
#on_path = '.*'
#hook_source = '''
#  source ~/.vim/rc/syntastic.vim
#'''

#[[plugins]]
#repo = 'neomake/neomake'
#if = '''has('nvim')'''
#on_path = '.*'
#hook_source = '''
#  source ~/.vim/rc/neomake.vim
#'''

[[plugins]]
repo = 'wannesm/wmgraphviz.vim'
on_ft = ['dot', 'plantuml', 'markdown']

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = ['plantuml', 'markdown']

[[plugins]]
repo = 'Shougo/junkfile.vim'
on_map = ['Junkfile', 'JunkfileDiary']
hook_source = '''
  command! -nargs=0 JunkfileDiary call junkfile#open_immediately(strftime('%Y-%m-%d.md'))
'''

[[plugins]]
repo = 'freitass/todo.txt-vim'
on_ft = 'todo'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml', 'markdown']

[[plugins]]
repo = 'osyo-manga/vim-precious'
on_path = '.*'
hook_source = '''
  let g:precious_enable_switch_CursorMoved = {
  \   "help" : 0
  \}
  let g:precious_enable_switchers = {
  \  "markdown" : {
  \    "setfiletype" : 0
  \  },
  \}
  augroup preciousSyntaxSwitch
    autocmd!
    autocmd User PreciousFileType let &l:syntax = precious#context_filetype()
  augroup END
'''

# [[plugins]]
# repo = 'mattn/sonictemplate-vim'
# on_path = '.*'

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']
hook_source = '''
  source ~/.vim/rc/neosnippet.vim
'''

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'
depends = ['vim-quickrun', 'vimproc.vim', 'shabadou.vim']
hook_source = '''
  " 書き込み後にシンタックスチェックを行う
  let g:watchdogs_check_BufWritePost_enable = 1

  " こっちは一定時間キー入力がなかった場合にシンタックスチェックを行う
  " バッファに書き込み後、1度だけ行われる
  let g:watchdogs_check_CursorHold_enable = 1
'''
on_path = '.*'

[[plugins]]
repo = 'jceb/vim-hier'
on_path = '.*'

[[plugins]]
repo = 'dannyob/quickfixstatus'
on_path = '.*'

[[plugins]]
repo = 'zchee/deoplete-zsh'
on_ft = 'zsh'

[[plugins]]
repo = 'mattn/gist-vim'
depends = 'mattn/webapi-vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = ['dockerfile', 'markdown']

[[plugins]]
repo = 'vim-scripts/dbext.vim'
on_path = '.*'
hook_source = '''
  let g:dbext_default_buffer_lines = 20
'''

[[plugins]]
repo = 'gorodinskiy/vim-coloresque'
on_ft = ['css', 'html', 'less', 'sass', 'scss', 'styles', 'vim']
