name: Emacs

on:
  push:
    paths:
      - ".github/workflows/emacs.yml"
      - "emacs/**/*.el"
      - "scripts/*"

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, macos-latest]
        emacs-verion: [26.3]

    steps:
    - uses: actions/checkout@v1
    - name: Setup emacs
      run: |
        source scripts/setup.sh
        source scripts/installers.sh
        setup
        install_essentials
        install_emacs ${{ matrix.emacs-version }}
    - name: Launch emacs
      run: |
        emacs -l emacs/init.el -batch
